###############################################################################
#
# Common builder image.
#
FROM alpine AS pdns-builder

RUN apk --update upgrade && \
    apk add ca-certificates curl && \
    apk add --virtual .build-depends \
            file g++ make boost-dev openssl-dev libsodium-dev lua-dev \
            net-snmp-dev protobuf-dev mariadb-dev postgresql-dev sqlite-dev \
            geoip-dev yaml-cpp-dev


###############################################################################
#
# Build the server.
#
FROM pdns-builder AS server-builder

ARG server_name=pdns
ARG server_ver=4.1.13

RUN echo "Building ${server_name} version ${server_ver}" && \
    curl -RL -O "https://downloads.powerdns.com/releases/${server_name}-${server_ver}.tar.bz2" && \
    tar xvfj "${server_name}-${server_ver}.tar.bz2" && \
    rm -f "${server_name}-${server_ver}.tar.bz2"

RUN cd "${server_name}-${server_ver}" && \
    ./configure \
      --sysconfdir=/etc/pdns \
      --mandir=/usr/share/man \
      --enable-libsodium \
      --with-sqlite3 \
      --enable-tools \
      --with-modules='bind gsqlite3' \
      --with-dynmodules='geoip gmysql gpgsql lua pipe random remote'

RUN cd "${server_name}-${server_ver}" && \
    make && \
    make install-strip

RUN apk del --purge .build-depends && \
    rm -rf /var/cache/apk/*


###############################################################################
#
# Final server image.
#
FROM alpine AS server

RUN apk --update upgrade && \
    apk add ca-certificates curl less man boost-program_options openssl \
            libsodium lua net-snmp protobuf mariadb-connector-c libpq \
            sqlite-libs geoip yaml-cpp && \
    rm -rf /var/cache/apk/*

RUN addgroup -g 2500 -S pdns && \
    adduser -u 2500 -S -D -G pdns pdns

COPY --from=server-builder /usr/local/bin/ /usr/local/bin/
COPY --from=server-builder /usr/local/sbin/ /usr/local/sbin/
COPY --from=server-builder /usr/local/lib/pdns/ /usr/local/lib/pdns/
COPY --from=server-builder /usr/share/man/man1/ /usr/share/man/man1/
COPY --from=server-builder /usr/local/share/doc/pdns/ /usr/local/share/doc/pdns/
COPY --from=server-builder /etc/pdns /etc/pdns/

RUN cp -p /etc/pdns/pdns.conf-dist \
          /etc/pdns/pdns.conf

ENTRYPOINT ["/usr/local/sbin/pdns_server"]
CMD ["--help"]

