###############################################################################
#
# Common builder image.
#
FROM alpine AS pdns-builder

RUN apk --update upgrade && \
    apk add ca-certificates curl && \
    apk add --virtual .build-depends \
            file g++ make boost-dev openssl-dev libsodium-dev lua-dev \
            net-snmp-dev protobuf-dev mariadb-dev postgresql-dev sqlite-dev \
            geoip-dev yaml-cpp-dev


###############################################################################
#
# Build the recursor.
#
FROM pdns-builder AS recursor-builder

ARG recursor_name=pdns-recursor
ARG recursor_ver=4.2.0

RUN echo "Building ${recursor_name} version ${recursor_ver}" && \
    curl -RL -O "https://downloads.powerdns.com/releases/${recursor_name}-${recursor_ver}.tar.bz2" && \
    tar xvfj "${recursor_name}-${recursor_ver}.tar.bz2" && \
    rm -f "${recursor_name}-${recursor_ver}.tar.bz2"

RUN cd "${recursor_name}-${recursor_ver}" && \
    ./configure \
      --sysconfdir=/etc/pdns \
      --mandir=/usr/share/man

RUN cd "${recursor_name}-${recursor_ver}" && \
    make && \
    make install-strip

RUN apk del --purge .build-depends && \
    rm -rf /var/cache/apk/*


###############################################################################
#
# Final recursor image.
#
FROM alpine AS recursor

RUN apk --update upgrade && \
    apk add ca-certificates curl less man boost-context openssl \
            libsodium lua net-snmp protobuf && \
    rm -rf /var/cache/apk/*

RUN addgroup -S pdns && \
    adduser -S -D -G pdns pdns

COPY --from=recursor-builder /usr/local/bin/ /usr/local/bin/
COPY --from=recursor-builder /usr/local/sbin/ /usr/local/sbin/
COPY --from=recursor-builder /usr/share/man/man1/ /usr/share/man/man1/
COPY --from=recursor-builder /etc/pdns/ /etc/pdns/

RUN cp -p /etc/pdns/recursor.conf-dist \
          /etc/pdns/recursor.conf

ENTRYPOINT ["/usr/local/sbin/pdns_recursor"]
CMD ["--help"]

